### ISSUE TITLE
Add the possibility of submitting `max_concurrent_base_workchains`

### ISSUE THREAD

**Issue by bastonero** [bastonero/aiida-vibroscopy#52]
The `PhononWorkChain` can spawn quite a few parallel `PwBaseWorkChain`, especially in low-symmetry systems. It would be ideal to add the capability to submit only a certain maximum number of them at a time, until the workchain runs out of them.

**Comment by cpignedoli** [comment]
Hi @bastonero we should discuss the possibility of bringing this to higher priority, we have started having issues with "realistic" systems (~100 atoms), we can discuss this in person in June and later update the issue.

**Comment by bastonero** [comment]
Hi @cpignedoli , thanks for reminding me this one. It should be actually quite easy, as the logic has already been implemented in `aiida-quantumespresso-hp`, so we can "simply copy/paste" it here and do some tests to see that everything works fine.
