### ISSUE TITLE
Missing f-string Specifier in PhononWorkChain

### ISSUE THREAD

**Issue by killercatempire** [bastonero/aiida-vibroscopy#61]
In `PhononWorkChain` in the `inspect_all_runs` method there is a missing f-string specifier on line 454 
that is causing the workchain to not report what the exit status for the subprocess that failed.
`'with exit status {workchain.exit_status}'` should be `f'with exit status {workchain.exit_status}'`

**Comment by bastonero** [comment]
Hello, in the main release of the code we don't have such WorkChain. I suppose you are referring to an Environ implementation, is it correct? I know a collaborator of mine that is working on this, but as you can inspect there's yet not official support.

**Comment by killercatempire** [comment]
My mistake, I meant `PhononWorkChain` I made a modified version that uses Environ.

**Comment by bastonero** [comment]
Thanks for reporting this. I am about to open a PR to fix this.
