### ISSUE TITLE
Add ionic contribution to dielectric constant

### ISSUE THREAD

**Issue by Sokseiha** [bastonero/aiida-vibroscopy#73]
It would be really great if we can also compute the ionic contribution to the dielectric constant as done in VASP and Materials Project. Currently, we have only the so-called ion-clamped (or high-frequency) dielectric constant but sometime it is necessary to have the total dielectric constant for example when we want to compute the correction for defect formation energies in which we allow the defect position to relaxed. The calculations should be very fast as we already have all the ingredients namely the Born effective charges and the interatomic force constant.
The expression of this ionic contribution can be found in this [slide](https://www.nersc.gov/assets/Uploads/VASP-lecture-Dielectric.pdf) (page 36)

**Comment by bastonero** [comment]
Hello, this is already possible actually! There is a function in VibrationalData that computes the complex dielectric function in the IR regime: run_complex_dielectric_function if I am not mistaken.
Then you can take the value at 0 frequency, which will give you the total dielectric constant (if you subtract the “electronic” dielectric constant, ie eps^infty, you recover the “ionic” dielectric constant.
