### ISSUE TITLE
Aiida_vibroscopy in Quantum Mobile 24.04.0

### ISSUE THREAD

**Issue by omamuyovwi** [bastonero/aiida-vibroscopy#83]
Dear Developers,

I am try using the aiida_vibroscopy for raman properties calculation. I have the latest version of Quantum Mobile, however, I get the following message when I try to use this aiida plugin :

ModuleNotFoundError: No module named 'aiida_vibroscopy'

Which version of Quantum Mobile works best for the aiida_vibroscopy?

Thank you.

Omamuyovwi Rita JOLAYEMI
Nigeria

**Comment by bastonero** [comment]
Dear Rita, thanks a lot for the interest in using our code! 
Quantum Mobile doesn’t come with aiida-vibroscopy pre-installed. But it’s very easy! You should be able to install it in the terminal (where aiida is installed) by using the command “pip install aiida-vibroscopy; verdi daemon restart”
Let me know if you have any issues!
Best
